[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/Users/mike_e_dubs/Repositories/hera_opm/pipelines/h3c/rtp/v1/task_scripts"
source_script = "~/.bashrc"
conda_env = "mw_nrao_py36"
base_mem = 64000
base_cpu = 1
atch_system = "slurm"
default_queue = "hera,master"

[SSINS_OPTS]
streak_sig = 20.0
other_sig = 5.0
tb_aggro = 0.5

[WorkFlow]
actions = ["SSINS"]

[SSINS]
args = ["${SSINS_OPTS:streak_sig}", "${SSINS_OPTS:other_sig}",
        "${SSINS_OPTS:tb_aggro}", "{obsid_list}"]
