[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/home/obs/src/hera_opm/pipelines/h3c/rtp/v1/task_scripts"
source_script = "~/.bashrc"
conda_env = "RTP"
base_mem = 8000
base_cpu = 1
batch_system = "slurm"

[WorkFlow]
actions = ["SETUP", "EXTRACT_HH", "UPLOAD_HH", "ANT_METRICS", "ADD_MC_ANT_METRICS", "ADD_LIBRARIAN_ANT_METRICS", "ADD_RTP_PROCESS_RECORD", "TEARDOWN"]

[EXTRACT_HH]
args = ["{basename}"]

[ANT_METRICS]
args = ["{basename}"]

[ADD_MC_ANT_METRICS]
args = ["{basename}"]

[ADD_LIBRARIAN_ANT_METRICS]
args = ["{basename}"]

[UPLOAD_HH]
args = ["{basename}"]

[ADD_RTP_PROCESS_RECORD]
args = ["{basename}", "${WorkFlow:actions}"]
