[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/home/obs/src/hera_opm/pipelines/h3c/rtp/v1/task_scripts"
source_script = "~/.bashrc"
conda_env = "RTP"
base_mem = 8000
base_cpu = 1
batch_system = "slurm"
default_queue = "hera,bigmem"
mandc_report = true

[ANT_METRICS_OPTS]
crossCut = 5.0
deadCut = 5.0
extension = ".ant_metrics.hdf5"
vis_format = "uvh5"

[WorkFlow]
actions = ["SETUP", "EXTRACT_HH", "UPLOAD_HH", "ANT_METRICS",
           "ADD_LIBRARIAN_ANT_METRICS", "ADD_MC_ANT_METRICS",
           "ADD_RTP_PROCESS_RECORD", "TEARDOWN"]

[EXTRACT_HH]
args = ["{basename}"]

[ANT_METRICS]
args = ["{basename}", "${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}", "${ANT_METRICS_OPTS:extension}",
        "${ANT_METRICS_OPTS:vis_format}"]

[ADD_LIBRARIAN_ANT_METRICS]
args = ["{basename}", "${ANT_METRICS_OPTS:extension}"]

[ADD_MC_ANT_METRICS]
args = ["{basename}", "${ANT_METRICS_OPTS:extension}"]

[UPLOAD_HH]
args = ["{basename}"]

[ADD_RTP_PROCESS_RECORD]
args = ["{basename}", "${WorkFlow:actions}"]
