sudo: required
dist: trusty
os:
  - linux
env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
install:
  - git fetch --unshallow --tags
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create environment and install dependencies
  - conda create -q -n testenv python="$PYTHON_VERSION"
  - source activate testenv
  - conda install pytest pytest-runner pip numpy scipy matplotlib six toml nose astropy ephem pycodestyle coveralls h5py scikit-learn six pandas coverage
  - conda install -c conda-forge aipy pyephem
  - pip install git+https://github.com/HERA-Team/pyuvdata.git
  - pip install git+https://github.com/HERA-Team/linsolve.git
  - pip install git+https://github.com/HERA-Team/hera_qm.git
  - pip install git+https://github.com/HERA-Team/uvtools.git
  - pip install git+https://github.com/HERA-Team/hera_cal.git
  - pip install git+https://github.com/HERA-Team/casa_imaging.git
  - conda list
script:
  - coverage run --source=hera_opm setup.py test
  - pycodestyle --ignore=E501,W503
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
