[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h1c/idr2/v2/task_scripts"
conda_env = "hera"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/pipelines/h1c/idr2/v2/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "jsdillon+makeflow@berkeley.edu"

[REDCAL_OPTS]
ant_z_thresh = 4.0
solar_horizon = 0.0
nInt_to_load = 8
flag_nchan_low = 50
flag_nchan_high = 50
min_bl_cut = 15
max_bl_cut = 90

[ABSCAL_OPTS]
model_files_glob = "/lustre/aoc/projects/hera/nkern/idr3_abscal_models/full_model/zen.2458042.?????.HH.uvRXLS.uvh5"
filetype = 'uvh5'
phs_max_iter = 100
phs_conv_crit = 1e-6
refant = 53 #TODO: figure out what to do about this
max_bl_cut = 100
edge_cut = 100
antflag_thresh = 0.0

# [CAL_XRFI_OPTS]
# TODO: UPDATE

# [DELAY_XRFI_OPTS]
# TODO: UPDATE

[CAL_SMOOTH_OPTS]
freq_scale = 10
time_scale = 1800
tol = 1e-9
filter_mode = "rect"
window = "tukey"
skip_wgt = 0.1
maxiter = 100
alpha = 0.3
antflag_thresh = 0.0

[DELAY_OPTS]
partial_load_Nbls = 100
standoff = 15
horizon = 1
tol = 1e-9
window = "tukey"
skip_wgt = 0.1
maxiter = 100
alpha = 0.5

# [REFLECTIONS_OPTS]
# TODO: UPDATE

############################################################################################################

[WorkFlow]
actions = ["EXTRACT_AUTOS", "REDCAL", "ABSCAL", #FIRSTCAL_METRICS, CAL_XRFI, DELAY_XRFI, CAL_SMOOTH, DELAY, NOISE, REFLECTIONS
           ]
[EXTRACT_AUTOS]
args = ["{basename}"]

[REDCAL]
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}", 
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}", "${REDCAL_OPTS:max_bl_cut}"]

[ABSCAL]
prereqs = "REDCAL"
mem = 32000
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:filetype}",
"${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:refant}", "${ABSCAL_OPTS:max_bl_cut}",
"${ABSCAL_OPTS:edge_cut}", "${ABSCAL_OPTS:antflag_thresh}"]

# [FIRSTCAL_METRICS]
# prereqs = "REDCAL"
# args = TODO: UPDATE

# [CAL_XRFI]
# prereqs = "ABSCAL"
# args = TODO: UPDATE

# [DELAY_XRFI]
# prereqs = "CAL_XRFI"
# args = TODO: UPDATE

[CAL_SMOOTH]
prereqs = "DELAY_XRFI"
time_prereqs = "DELAY_XRFI"
n_time_neighbors = "all"
mem = 32000
args = ["{basename}", "${CAL_SMOOTH_OPTS:freq_scale}", "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}", "${CAL_SMOOTH_OPTS:filter_mode}", "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:skip_wgt}", "${CAL_SMOOTH_OPTS:maxiter}",
        "${CAL_SMOOTH_OPTS:alpha}", "${CAL_SMOOTH_OPTS:antflag_thresh}"]

[DELAY]
prereqs = "CAL_SMOOTH"
time_prereqs = "CAL_SMOOTH"
n_time_neighbors = "all"
args = ["{basename}", "${DELAY_OPTS:partial_load_Nbls}", "${DELAY_OPTS:standoff}", 
        "${DELAY_OPTS:horizon}", "${DELAY_OPTS:tol}", "${DELAY_OPTS:window}",
        "${DELAY_OPTS:skip_wgt}", "${DELAY_OPTS:maxiter}", "${DELAY_OPTS:alpha}"]

[NOISE]
prereqs = "CAL_SMOOTH"
time_prereqs = "CAL_SMOOTH"
n_time_neighbors = "all"
args = ["{basename}"]

# [REFLECTIONS]
# prereqs = "CAL_SMOOTH"
# time_prereqs = "CAL_SMOOTH"
# n_time_neighbors = "all"
# args = TODO: UPDATE
