[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/hera_opm/H1C_IDR3/bad_ants/"
conda_env = "hera"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/hera_opm/H1C_IDR3/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "jsdillon+makeflow@berkeley.edu"

[REDCAL_OPTS]
ant_z_thresh = 4.0
solar_horizon = 0.0
nInt_to_load = 8
flag_nchan_low = 50
flag_nchan_high = 50

[ABSCAL_OPTS]
model_files_glob = "/lustre/aoc/projects/hera/nkern/idr3_abscal_models/full_model/zen.2458042.?????.HH.uvRXLS.uvh5"
filetype = 'uvh5'
phs_max_iter = 100
phs_conv_crit = 1e-6
refant = 53
max_bl_cut = 100
edge_cut = 100
solar_horizon = 0.0
antflag_thresh = 0.0

[WorkFlow]
actions = ["REDCAL", "ABSCAL"]

[REDCAL]
prereqs = "FIRSTCAL_METRICS"
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}", 
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:nInt_to_load}"]

[ABSCAL]
prereqs = "REDCAL"
mem = 32000
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:filetype}",
"${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:refant}", "${ABSCAL_OPTS:max_bl_cut}",
"${ABSCAL_OPTS:edge_cut}", "${ABSCAL_OPTS:solar_horizon}", "${ABSCAL_OPTS:antflag_thresh}"]
