[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h1c/idr2/v2/task_scripts"
conda_env = "hera"
base_mem = 10000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "jsdillon+makeflow@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = True
sigma = 5
min_N = 5
rephase = True
ntimes_per_file = 60
dlst = "None"
lst_start = 0.0
fixed_lst_start = True
vis_units = "Jy"
parallelize = True
file_ext = "grp1.of1.{}.{}.{:7.5f}.HH.OCRS.uvh5"
outdir = "./"
parent_dir = "./"
data_files = ["data/zen.2458043.*.HH.OCRS.uvh5",
              "data/zen.2458044.*.HH.OCRS.uvh5",
              "data/zen.2458045.*.HH.OCRS.uvh5"]
calibration = "smooth_abs.calfits"

[WorkFlow]
actions = "LSTBIN"

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "calibration"]
