[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/hera_opm/H1C_IDR3/bad_ants/"
conda_env = "hera"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/hera_opm/H1C_IDR3/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "jsdillon+makeflow@berkeley.edu"

[REDCAL_OPTS]
ant_z_thresh = 4.0
solar_horizon = 0.0
nInt_to_load = 8
flag_nchan_low = 50
flag_nchan_high = 50
min_bl_cut = 15
max_bl_cut = 90

# [ABSCAL_OPTS]
# TODO: UPDATE

# [CAL_XRFI_OPTS]
# TODO: UPDATE

# [DELAY_XRFI_OPTS]
# TODO: UPDATE

# [CAL_SMOOTH_OPTS]
# TODO: UPDATE
# time_scale = 1800
# mirror_sigmas = 5
# freq_scale = 10
# tol = 1e-9
# window = "tukey"
# skip_wgt = 0.1
# maxiter = 100
# alpha = 0.3
# antflag_thresh = 0.0

# [DELAY_OPTS]
# TODO: UPDATE
# standoff = 15
# horizon = 1
# tol = 1e-9
# window = "tukey"
# skip_wgt = 0.1
# maxiter = 100
# alpha = 0.5

# [NOISE_OPTS]
# TODO: UPDATE

# [REFLECTIONS_OPTS]
# TODO: UPDATE

############################################################################################################

[WorkFlow]
actions = ["EXTRACT_AUTOS", "REDCAL", # FIRSTCAL_METRICS, ABSCAL, CAL_XRFI, DELAY_XRFI, CAL_SMOOTH, DELAY, NOISE, REFLECTIONS
           ]

[EXTRACT_AUTOS]
args = ["{basename}"]

[REDCAL]
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}", 
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}", "${REDCAL_OPTS:max_bl_cut}"]

# [FIRSTCAL_METRICS]
# prereqs = "REDCAL"
# args = TODO: UPDATE

# [ABSCAL]
# prereqs = "REDCAL"
# args = TODO: UPDATE

# [CAL_XRFI]
# prereqs = "ABSCAL"
# args = TODO: UPDATE

# [DELAY_XRFI]
# prereqs = "CAL_XRFI"
# args = TODO: UPDATE

# [CAL_SMOOTH]
# prereqs = "DELAY_XRFI"
# time_prereqs = "DELAY_XRFI"
# n_time_neighbors = "all"
# mem = 32000
# args = TODO: UPDATE
#         ["{basename}", "${CAL_SMOOTH_OPTS:time_scale}", "${CAL_SMOOTH_OPTS:mirror_sigmas}",
#         "${CAL_SMOOTH_OPTS:freq_scale}", "${CAL_SMOOTH_OPTS:tol}", "${CAL_SMOOTH_OPTS:window}",
#         "${CAL_SMOOTH_OPTS:skip_wgt}", "${CAL_SMOOTH_OPTS:maxiter}",
#         "${CAL_SMOOTH_OPTS:alpha}", "${CAL_SMOOTH_OPTS:antflag_thresh}"]

# [DELAY]
# prereqs = "CAL_SMOOTH"
# time_prereqs = "CAL_SMOOTH"
# n_time_neighbors = "all"
# args = TODO: UPDATE
#         ["{basename}", "${DELAY_OPTS:standoff}", "${DELAY_OPTS:horizon}", "${DELAY_OPTS:tol}",
#         "${DELAY_OPTS:window}", "${DELAY_OPTS:skip_wgt}", "${DELAY_OPTS:maxiter}",
#         "${DELAY_OPTS:alpha}"]

# [REFLECTIONS]
# prereqs = "CAL_SMOOTH"
# time_prereqs = "CAL_SMOOTH"
# n_time_neighbors = "all"
# args = TODO: UPDATE

# [REFLECTIONS]
# prereqs = "CAL_SMOOTH"
# time_prereqs = "CAL_SMOOTH"
# n_time_neighbors = "all"
# args = TODO: UPDATE

