NOTE TO E-DUBBS: This file is borked. Talk to Adam or Josh about updating
for new chunking keywords. Or check other tomls.

[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/idr2/v1/task_scripts"
source_script = "~/.bashrc"
conda_env = "python3"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/idr2/v1/bad_ants"
base_mem = 16000
base_cpu = 1
timeout = "24h"

[ANT_METRICS_OPTS]
crossCut = 5.0
deadCut = 5.0
extension = ".ant_metrics.hdf5"
vis_format = "uvh5"

[NB_OPTS]
basenbdir = '/users/jsdillon/Libraries/H3C_plots'

[REDCAL_OPTS]
ant_z_thresh = 4
solar_horizon = 0.0
nInt_to_load = 10
flag_nchan_low = 0
flag_nchan_high = 0
oc_maxiter = 5000
min_bl_cut = 15
max_bl_cut = 100
iter0_prefix = ".iter0"
good_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok"
# good_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok,dish_maintenance,dish_ok,RF_maintenance,RF_ok,known_bad,not_connected"

[ABSCAL_OPTS]
model_files_glob = "'/lustre/aoc/projects/hera/H3C/abscal_models/RIMEz_Red_Only_Rescaled/zen.2458790.?????.uvh5'"
nInt_to_load = 6
min_bl_cut = 40.0
max_bl_cut = 140.0
phs_max_iter = 100
phs_conv_crit = 1e-6
edge_cut = 100

[XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init = 5.0
sig_adj = 2.0

[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0
nsig_t = 7.0
nsig_f_adj = 3.0
nsig_t_adj = 3.0

[CAL_SMOOTH_OPTS]
freq_scale = 10
time_scale = 21600
tol = 1e-6
filter_mode = "rect"
window = "tukey"
maxiter = 100
alpha = 0.3
freq_threshold = 1.0
time_threshold = 1.0
ant_threshold = 0.5
lst_blacklists = "2.5-4.3 6.5-9.5"

[IMAGING_OPTS]
casa = "/home/casa/packages/RHEL7/release/casa-release-5.1.0-68/bin/casa"
casa_imaging_scripts = "/users/heramgr/hera_software/casa_imaging/scripts"
calibration = "smooth_abs.calfits"

[DELAY_OPTS]
nbls_partial = 1
output_label = "tol_1e-9.standoff_200"
spw0 = 0
spw1 = 250
tol = 1e-9
standoff = 200
cache_dir = "/lustre/aoc/projects/hera/aoc/aewallwi/filter_cache/"
calibration = "smooth_abs.calfits"




############################################################################################################

[WorkFlow]
actions = [#"FIX_DATAFILE",
           "EXTRACT_AUTOS",
           "ANT_METRICS",
           "REDCAL",
           "FIRSTCAL_METRICS",
           "ABSCAL",
           "XRFI",
           "XRFI_DAY_THRESHOLD",
           "CAL_SMOOTH",
           "MAKE_REDCAL_NOTEBOOK",
           "UPDATE_OMNISOL",
           "NOISE",
           "IMAGING",
           "DAYENU_FOREGROUND_SUBTRACTION"
           "MAKE_NOTEBOOK"]

[FIX_DATAFILE]
args = "{basename}"

[EXTRACT_AUTOS]
args = ["{basename}"]

[ANT_METRICS]
# prereqs = "FIX_DATAFILE"
mem = 64000
args = ["{basename}", "${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}", "${ANT_METRICS_OPTS:extension}",
        "${ANT_METRICS_OPTS:vis_format}"]

[REDCAL]
prereqs = "ANT_METRICS"
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}", "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}", "${REDCAL_OPTS:iter0_prefix}",
        "${ANT_METRICS_OPTS:extension}", "${REDCAL_OPTS:good_statuses}"]

[FIRSTCAL_METRICS]
prereqs = "REDCAL"
args = "{basename}"

[MAKE_REDCAL_NOTEBOOK]
prereqs = "REDCAL"
chunk_size = "all"
mem = 128000
args = ["{basename}", "{prev_basename}", "${NB_OPTS:basenbdir}"]

[ABSCAL]
prereqs = "REDCAL"
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:nInt_to_load}",
        "${ABSCAL_OPTS:min_bl_cut}", "${ABSCAL_OPTS:max_bl_cut}", "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:edge_cut}"]

[XRFI]
prereqs = "ABSCAL"
mem = 64000
args = ["{basename}", "${XRFI_OPTS:kt_size}", "${XRFI_OPTS:kf_size}", "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}"]


[XRFI_DAY_THRESHOLD]
prereqs = "XRFI"
chunk_size = "all"
args = ["{basename}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_f}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}"]

[CAL_SMOOTH]
prereqs = "XRFI_DAY_THRESHOLD"
chunk_size = "all"
mem = 64000
args = ["{basename}", "${CAL_SMOOTH_OPTS:freq_scale}", "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}", "${CAL_SMOOTH_OPTS:filter_mode}", "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:maxiter}", "${CAL_SMOOTH_OPTS:alpha}", "${CAL_SMOOTH_OPTS:freq_threshold}",
        "${CAL_SMOOTH_OPTS:time_threshold}", "${CAL_SMOOTH_OPTS:ant_threshold}", "${CAL_SMOOTH_OPTS:lst_blacklists}"]

[UPDATE_OMNISOL]
prereqs = "CAL_SMOOTH"
chunk_size = "all"
args = ["{basename}"]

[NOISE]
prereqs = "CAL_SMOOTH"
chunk_size = "all"
args = ["{basename}"]

[IMAGING]
prereqs = "CAL_SMOOTH"
chunk_size = "all"
mem = 96000
args = ["{basename}", "${IMAGING_OPTS:casa}", "${IMAGING_OPTS:casa_imaging_scripts}", "${IMAGING_OPTS:calibration}"]

[MAKE_NOTEBOOK]
prereqs = "ANT_METRICS"
chunk_size = "all"
mem = 128000
args = ["{basename}", "{prev_basename}", "${NB_OPTS:basenbdir}"]

[DELAY]
prereqs = "CAL_SMOOTH"
chunk_size = "all"
mem = 64000
args = ["{basename}", "${DELAY_OPTS:calibration}", "${DELAY_OPTS:nbls_partial}", "${DELAY_OPTS:output_label}",
        "${DELAY_OPTS:spw0}", "${DELAY_OPTS:spw1}", "${DELAY_OPTS:tol}", "${DELAY_OPTS:standoff}", "${DELAY_OPTS:cache_dir}"]
