[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/idr2/v1/task_scripts"
source_script = "~/.bashrc"
conda_env = "python3"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/idr2/v1/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"

############################################################################################################

[WorkFlow]
actions = ["FIX_DATAFILE"]

[FIX_DATAFILE]
args = "{basename}"
