name: hera_opm_tests
channels:
  - defaults
  - conda-forge
dependencies:
  - aipy
  - astropy
  - flake8
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-runner
  - pyuvdata
  - scipy
  - toml
  - scikit-learn
  - pip:
      - hera-calibration
      - uvtools
      - git+https://github.com/HERA-Team/casa_imaging.git
