[Options]
makeflow_type = "analysis"
pols = ["xx", "xy", "yx", "yy"]
path_to_do_scripts = "/users/heramgr/hera_software/hera_opm/pipelines/h1c/idr2/v1/task_scripts"
conda_env = "hera"
ex_ants_path = "/users/heramgr/hera_software/hera_opm/pipelines/h1c/idr2/v1/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "plaplant@sas.upenn.edu"

[OMNI_APPLY_OPTS]
flag_nchan_low = 50
flag_nchan_high = 50

[ABSCAL_OPTS]
model_files_glob = "/lustre/aoc/projects/hera/H1C_IDR2/abscal_models/zen.2458116.*.pp.HH.uvXRS2"
phs_max_iter = 100
phs_conv_crit = 1e-6
refant = 53
bl_cut = 100
edge_cut = 100
solar_horizon = 0.0
antflag_thresh = 0.0

[ABSCAL_APPLY_OPTS]
flag_nchan_low = 50
flag_nchan_high = 50
vis_units = 'Jy'

[CAL_XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init = 6
sig_adj = 2
px_threshold = 0.1
freq_threshold = 0.5
time_threshold = 0.05

[DELAY_XRFI_OPTS]
standoff = 15
horizon = 1
tol = 1e-7
window = "tukey"
skip_wgt = 0.1
maxiter = 100
alpha = 0.5
kt_size = 8
kf_size = 8
sig_init = 6
sig_adj = 2
px_threshold = 0.1
freq_threshold = 0.25
time_threshold = 0.05

[DELAY_XRFI_APPLY_OPTS]
extension = "R"
output_npz_ext = ".flags.applied.npz"

[CAL_SMOOTH_OPTS]
time_scale = 1800
mirror_sigmas = 5
freq_scale = 10
tol = 1e-9
window = "tukey"
skip_wgt = 0.1
maxiter = 100
alpha = 0.3
antflag_thresh = 0.0

[CAL_SMOOTH_APPLY_OPTS]
flag_nchan_low = 50
flag_nchan_high = 50
vis_units = 'Jy'

[DELAY_OPTS]
standoff = 15
horizon = 1
tol = 1e-9
window = "tukey"
skip_wgt = 0.1
maxiter = 100
alpha = 0.5

[WorkFlow]
actions = ["FIRSTCAL", "FIRSTCAL_METRICS", "OMNICAL", "OMNICAL_METRICS",
           "OMNI_APPLY", "ABSCAL", "ABSCAL_APPLY", "CAL_XRFI", "DELAY_XRFI",
           "DELAY_XRFI_APPLY", "CAL_SMOOTH", "CAL_SMOOTH_APPLY", "DELAY",
           "CLEAN_OMNI_APPLY", "CLEAN_ABSCAL_APPLY"]

[FIRSTCAL]
args = ["{basename}", "${Options:ex_ants_path}"]

[FIRSTCAL_METRICS]
args = "{basename}"

[OMNICAL]
prereqs = "FIRSTCAL_METRICS"
args = ["{basename}", "${Options:ex_ants_path}"]
mem = 10000

[OMNICAL_METRICS]
prereqs = "OMNICAL"
args = "{basename}"

[OMNI_APPLY]
prereqs = "OMNICAL_METRICS"
args = ["{basename}", "${OMNI_APPLY_OPTS:flag_nchan_low}", "${OMNI_APPLY_OPTS:flag_nchan_high}"]

[ABSCAL]
prereqs = "OMNI_APPLY"
mem = 16000
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:refant}", "${ABSCAL_OPTS:bl_cut}",
        "${ABSCAL_OPTS:edge_cut}", "${ABSCAL_OPTS:solar_horizon}", "${ABSCAL_OPTS:antflag_thresh}"]

[ABSCAL_APPLY]
prereqs = "ABSCAL"
args = ["{basename}", "${ABSCAL_APPLY_OPTS:flag_nchan_low}", "${ABSCAL_APPLY_OPTS:flag_nchan_high}",
        "${ABSCAL_APPLY_OPTS:vis_units}"]

[CAL_XRFI]
prereqs = "ABSCAL"
args = ["{basename}", "${CAL_XRFI_OPTS:kt_size}",
        "${CAL_XRFI_OPTS:kf_size}", "${CAL_XRFI_OPTS:sig_init}", "${CAL_XRFI_OPTS:sig_adj}",
        "${CAL_XRFI_OPTS:px_threshold}", "${CAL_XRFI_OPTS:freq_threshold}",
        "${CAL_XRFI_OPTS:time_threshold}"]

[DELAY_XRFI]
prereqs = ["CAL_XRFI", "ABSCAL_APPLY"]
args = ["{basename}", "${Options:ex_ants_path}", "${DELAY_XRFI_OPTS:standoff}",
        "${DELAY_XRFI_OPTS:horizon}", "${DELAY_XRFI_OPTS:tol}", "${DELAY_XRFI_OPTS:window}",
        "${DELAY_XRFI_OPTS:skip_wgt}", "${DELAY_XRFI_OPTS:maxiter}", "${DELAY_XRFI_OPTS:alpha}",
        "${DELAY_XRFI_OPTS:kt_size}", "${DELAY_XRFI_OPTS:kf_size}", "${DELAY_XRFI_OPTS:sig_init}",
        "${DELAY_XRFI_OPTS:sig_adj}", "${DELAY_XRFI_OPTS:px_threshold}",
        "${DELAY_XRFI_OPTS:freq_threshold}", "${DELAY_XRFI_OPTS:time_threshold}"]

[DELAY_XRFI_APPLY]
prereqs = "DELAY_XRFI"
args = ["{basename}", "${DELAY_XRFI_APPLY_OPTS:extension}",
        "${DELAY_XRFI_APPLY_OPTS:output_npz_ext}"]

[CAL_SMOOTH]
prereqs = "DELAY_XRFI_APPLY"
time_prereqs = "DELAY_XRFI_APPLY"
n_time_neighbors = "all"
mem = 32000
args = ["{basename}", "${CAL_SMOOTH_OPTS:time_scale}", "${CAL_SMOOTH_OPTS:mirror_sigmas}",
        "${CAL_SMOOTH_OPTS:freq_scale}", "${CAL_SMOOTH_OPTS:tol}", "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:skip_wgt}", "${CAL_SMOOTH_OPTS:maxiter}",
        "${CAL_SMOOTH_OPTS:alpha}", "${CAL_SMOOTH_OPTS:antflag_thresh}"]

[CAL_SMOOTH_APPLY]
prereqs = "CAL_SMOOTH"
time_prereqs = "CAL_SMOOTH"
n_time_neighbors = "all"
args = ["{basename}", "${CAL_SMOOTH_APPLY_OPTS:flag_nchan_low}",
        "${CAL_SMOOTH_APPLY_OPTS:flag_nchan_high}", "${CAL_SMOOTH_APPLY_OPTS:vis_units}"]

[DELAY]
prereqs = "CAL_SMOOTH"
args = ["{basename}", "${DELAY_OPTS:standoff}", "${DELAY_OPTS:horizon}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:window}", "${DELAY_OPTS:skip_wgt}", "${DELAY_OPTS:maxiter}",
        "${DELAY_OPTS:alpha}"]

[CLEAN_OMNI_APPLY]
prereqs = "DELAY"
args = "{basename}"

[CLEAN_ABSCAL_APPLY]
prereqs = "DELAY"
args = "{basename}"
